global:
  scrape_interval: 5s

scrape_configs:
  - job_name: transaction-producer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["transaction-producer:8081"]

  - job_name: balance-consumer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["balance-consumer:8082"]

  - job_name: fraud-watcher
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["fraud-watcher:8083"]