server:
  port: 8082

spring:
  application:
    name: balance-consumer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: balance-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.bankstream.balanceconsumer.infrastructure.adapter.in.messaging
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.bankstream.balanceconsumer.infrastructure.adapter.in.messaging.TransactionEvent

app:
  kafka:
    topic:
      transactions: transactions

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: balance-consumer

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bankstream: INFO