server:
  port: 8081

spring:
  application:
    name: transaction-producer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all

app:
  kafka:
    topic:
      transactions: transactions

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: transaction-producer

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bankstream: INFO